# Lazymc requires that the minecraft server have a static IP.
#
# To ensure that our servers have a static IP we need to create
# a network for our services to use.
#
# By default, Docker uses 172.17.0.0/16 subnet range.
# So we need to create a new network in a different subnet
# See the readme for more information.
#
# Please ensure that the subnet falls within the private CIDRs:
# https://datatracker.ietf.org/doc/html/rfc1918#section-3
#
# And that it is not in use by anything else.
networks:
  minecraft-network:
    driver: bridge    
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  geyser:
    image: portiz93/geysermc-proxy:latest
    networks:
      minecraft-network:
        ipv4_address: 172.28.0.4
    restart: unless-stopped
    environment:
      JAVA_ADDRESS: lazymc
      JAVA_PORT: 25565
      JAVA_AUTH_TYPE: floodgate
    ports:
      - "19132:19132/udp"
    volumes:
      - geyser-data:/Geyser/data
      - ./minecraft-data/plugins/floodgate/key.pem:/Geyser/floodgate/key.pem:ro
  lazymc:
    image: ghcr.io/joesturge/lazymc-docker-proxy:latest
    # the IPs should start at .2 as .1 is reserved for the gateway
    networks:
      minecraft-network:
        ipv4_address: 172.28.0.2
    restart: unless-stopped
    volumes:
      # you should mount the minecraft server dir under /server, using read only.
      - ./minecraft-data:/server:ro
      # you need to supply the docker socket, so that the container can run docker command
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      # lazymc-docker-proxy acts as a proxy, so there is
      # no need to expose the server port on the Minecraft container
      - "25565:25565"
  mc:
    image: itzg/minecraft-server
    pull_policy: daily
    mem_limit: 2g
    # Assign a static IP to the server container
    networks:
      minecraft-network:
        ipv4_address: 172.28.0.3
    # We need to add a label here so that lazymc-docker-proxy knows which
    # container to manage
    labels:
      # Set lazymc.enabled to true to enable lazymc on this container
      - lazymc.enabled=true
      # Required to find the container to manage it
      - lazymc.group=mc
      # Point to the service name of the Minecraft server
      - lazymc.server.address=mc:25565
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: 2G
      PLUGINS: |
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
      OPS: BoilingFuncat3
    tty: true
    # This container should be managed solely by the lazymc container
    # so set restart to no, or else the container will start again...
    restart: no
    stdin_open: true
    volumes:
      - ./minecraft-data:/data

volumes:
  data:
  geyser-data:
